### ISSUE TITLE
Exercise 1: Teddy activities

### ISSUE THREAD

**Issue by katyhuff** [arfc/cyclus.github.com#2]
When solving this, please **make your PR to the tutorial branch of this repository**. The master branch is being kept in sync with the cyclus/cyclus.github.com(master) branch. You are in charge of changes to the following files. In particular, improve grammar where necessary, break up large blocks of text with bold text, and streamline various pieces where notes were made in the arfc group meeting [doc](https://docs.google.com/document/d/1A7sg5Q4G-kNjPfGJ208egn_vetLW-l7hUy1cBaR_vy4/edit#)

Exercise 1: 

- [x] add_proto
- [x] add_reg_inst

**Comment by jbae11** [comment]
# 10 is merged

**Comment by katyhuff** [comment]
^ to link to the issue, there can't be a space between the hash and the number. (if there's a space, it becomes a heading)

#10
