### ISSUE TITLE
Exercise 1: Gwen Activities

### ISSUE THREAD

**Issue by katyhuff** [arfc/cyclus.github.com#3]
When solving this, please **make your PR to the tutorial branch of this repository**. The master branch is being kept in sync with the cyclus/cyclus.github.com(master) branch. You are in charge of changes to the following files. In particular, streamline tutorial experience, improve grammar where necessary, break up large blocks of text with bold text, and streamline various pieces where notes were made in the arfc group meeting [doc](https://docs.google.com/document/d/1A7sg5Q4G-kNjPfGJ208egn_vetLW-l7hUy1cBaR_vy4/edit#)

Exercise 1: 

- [x] launch_cyclus 
- [x] run_cyclus_native

**Comment by gwenchee** [comment]
In launch_cyclus.rst page, it discusses Working with Cyclus in the Cloud. Do we want to continue supporting this capability, since it was meant to be used with Cyclist. Should this page be depreciated? What does everyone think? @katyhuff @KennellyT @jbae11 @gtw2

**Comment by jbae11** [comment]
I think the cloud and cyclist mentions should generally be gone..?

**Comment by gtw2** [comment]
I believe in the meeting we talked about keeping it for now, although if nothing is being done with the cloud I don't see why we couldn't remove it to make installation clearer for the tutorial

**Comment by katyhuff** [comment]
This is really a Cyclus community manager question. I'll ask robert real quick.

**Comment by gwenchee** [comment]
Based on Robert's response, I will depreciate the launch_cyclus.rst page

**Comment by katyhuff** [comment]
Thanks!

**Comment by gwenchee** [comment]
In `run_cyclus_native`,  the webpage discusses that Cyclus can be used to run simulations on both a local and on a cloud. Should this page come right after The touring of ipynb page and they are given instructions on how to get the notebook on their local computer? @KennellyT
